# -*- coding: utf-8 -*-
"""
توليد وتصدير التقارير
"""

from datetime import datetime

def display_report(results):
    """عرض تقرير مفصل"""
    print(f"\n📊 **Analysis Results:**")
    print(f"   Length: {results['length']} characters")
    print(f"   Entropy: {results['entropy']} bits")
    print(f"   Score: {results['score']}/10")
    print(f"   Strength Level: {results['strength']}")
    
    if results['leet_detected']:
        print(f"   ⚠️  Leet substitutions detected")
    
    if results['issues']:
        print(f"\n🔴 **Detected Issues:**")
        for issue in results['issues']:
            print(f"   • {issue}")
    
    if results['recommendations']:
        print(f"\n✅ **Recommendations:**")
        for rec in results['recommendations']:
            print(f"   • {rec}")
    
    print(f"\n{'='*50}")

def display_summary(all_results):
    """عرض ملخص عام"""
    print(f"\n{'#'*60}")
    print(f"{'General Report Summary':^60}")
    print(f"{'#'*60}")
    
    total_passwords = len(all_results)
    strong_passwords = sum(1 for r in all_results if r['score'] >= 5)
    weak_passwords = sum(1 for r in all_results if r['score'] < 3)
    
    print(f"\n📈 **Statistics:**")
    print(f"   • Total Passwords: {total_passwords}")
    print(f"   • Strong Passwords: {strong_passwords}")
    print(f"   • Weak Passwords: {weak_passwords}")
    
    print(f"\n📋 **Passwords by Strength:**")
    for result in all_results:
        strength_color = "🟢" if result['score'] >= 5 else "🟡" if result['score'] >= 3 else "🔴"
        print(f"   {strength_color} {result['password']:20} → {result['strength']} ({result['score']}/10)")
    
    print(f"\n💡 **General Tips:**")
    print("   1. Use at least 12 characters")
    print("   2. Mix uppercase, lowercase, numbers, and symbols")
    print("   3. Avoid common words and predictable sequences")
    print("   4. Don't rely solely on leet substitutions")

def save_to_file(all_results):
    """حفظ التقرير في ملف"""
    with open('password_report.txt', 'w', encoding='utf-8') as f:
        f.write("="*60 + "\n")
        f.write("Password Strength Analysis Report\n")
        f.write("="*60 + "\n\n")
        f.write(f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        for i, result in enumerate(all_results, 1):
            f.write(f"\nPassword #{i}: {result['password']}\n")
            f.write(f"-" * 40 + "\n")
            f.write(f"Length: {result['length']} characters\n")
            f.write(f"Entropy: {result['entropy']} bits\n")
            f.write(f"Score: {result['score']}/10\n")
            f.write(f"Strength Level: {result['strength']}\n")
            
            if result['issues']:
                f.write(f"\nIssues:\n")
                for issue in result['issues']:
                    f.write(f"  • {issue}\n")
            
            if result['recommendations']:
                f.write(f"\nRecommendations:\n")
                for rec in result['recommendations']:
                    f.write(f"  • {rec}\n")
            
            f.write("\n" + "="*40 + "\n")
        
        # الإحصائيات
        strong = sum(1 for r in all_results if r['score'] >= 5)
        weak = sum(1 for r in all_results if r['score'] < 3)
        
        f.write(f"\n\n📊 Statistics Summary:\n")
        f.write(f"   • Total Passwords: {len(all_results)}\n")
        f.write(f"   • Strong Passwords: {strong}\n")
        f.write(f"   • Weak Passwords: {weak}\n")
        f.write(f"\nReport generated by Password Strength Analyzer\n")
